### ISSUE TITLE
Arduino tests fail

### ISSUE THREAD

**Issue by timotto** [timotto/arduinoci#1]
testSerialUTF8Decoder in Arduino-1.8.16/app/test/processing/app/SerialTest.java fails on `debian:stretch` with `openjdk-8` and on `debian:bullseye` with `openjdk-11`

```
    [junit] Running processing.app.SerialTest
    [junit] Testsuite: processing.app.SerialTest
    [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.573 sec
    [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.573 sec
    [junit] 
    [junit] Testcase: testSerialUTF8Decoder(processing.app.SerialTest): FAILED
    [junit] expected:<...01234567890123456789[?]0123456789> but was:<...01234567890123456789[?]0123456789>
    [junit] junit.framework.AssertionFailedError: expected:<...01234567890123456789[?]0123456789> but was:<...01234567890123456789[?]0123456789>
    [junit]     at processing.app.SerialTest.testSerialUTF8Decoder(SerialTest.java:56)
    [junit]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 
    [junit] 
    [junit] Test processing.app.SerialTest FAILED
```

**Comment by timotto** [comment]
commit 70d2abc27fab7a040d623989aa5660dc3e752aaa dropped the Arduino IDE GUI image
